# Generated by Django 5.0.6 on 2024-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('خانم', 'خانم'), ('آقا', 'آقا')], default='آقا', max_length=4),
        ),
    ]
