# Generated by Django 5.0.6 on 2024-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_appetizer_burger_drink_pasta_salad_remove_pizza_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appetizer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='burger',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salad',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
