# Generated by Django 5.0.6 on 2024-08-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('confirmed', 'تایید شده'), ('processing', 'در حال پردازش'), ('shipped', 'تحویل شده'), ('canceled', 'لغو شده')], default='pending', max_length=10),
        ),
    ]
