# Generated by Django 5.0.6 on 2024-08-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_alter_orderfood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
